# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/cryptix/wav";
    fetch = {
      type = "git";
      url = "https://github.com/cryptix/wav";
      rev = "8bdace674401f0bd3b63c65479b6a6ff1f9d5e44";
      sha256 = "18nyqv0ic35fs9fny8sj84c00vbxs8mnric6vr6yl42624fh5id6";
    };
  }
  {
    goPackagePath = "github.com/linuxdeepin/go-x11-client";
    fetch = {
      type = "git";
      url = "https://github.com/linuxdeepin/go-x11-client";
      rev = "c22b2003577b797880cd2cc6f4df6b16a092cda2";
      sha256 = "1lbgr6iy3hlg9dl6llls88cpy1v75pkkkppsh4mhjgvgly34wcjq";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "891ebc4b82d6e74f468c533b06f983c7be918a96";
      sha256 = "1rgw5gl2lc6bkmsx0fak84s6zdc1bhzfxgqg4mg4yh5hlnhpwrki";
    };
  }
  {
    goPackagePath = "pkg.deepin.io/lib";
    fetch = {
      type = "git";
      url = "https://github.com/linuxdeepin/go-lib.git";
      rev = "4d9427f49e7ce0d4c50beece26f9f86d473401e1";
      sha256 = "0lkyzlbxmq1mw0g3pqr5sasb6zr4rl9vb49907zq61aqhgk5dgb6";
    };
  }
]
