# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/alecthomas/template";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/template";
      rev = "a0175ee3bccc567396460bf5acd36800cb10c49c";
      sha256 = "0qjgvvh26vk1cyfq9fadyhfgdj36f1iapbmr5xp6zqipldz8ffxj";
    };
  }
  {
    goPackagePath = "github.com/alecthomas/units";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/units";
      rev = "2efee857e7cfd4f3d0138cc3cbb1b4966962b93a";
      sha256 = "1j65b91qb9sbrml9cpabfrcf07wmgzzghrl7809hjjhrmbzri5bl";
    };
  }
  {
    goPackagePath = "github.com/axgle/mahonia";
    fetch = {
      type = "git";
      url = "https://github.com/axgle/mahonia";
      rev = "3358181d7394e26beccfae0ffde05193ef3be33a";
      sha256 = "0b8wsrxmv8a0cqbnsg55lpf29pxy2zw8azvgh3ck664lqpcfybhq";
    };
  }
  {
    goPackagePath = "github.com/cryptix/wav";
    fetch = {
      type = "git";
      url = "https://github.com/cryptix/wav";
      rev = "8bdace674401f0bd3b63c65479b6a6ff1f9d5e44";
      sha256 = "18nyqv0ic35fs9fny8sj84c00vbxs8mnric6vr6yl42624fh5id6";
    };
  }
  {
    goPackagePath = "github.com/linuxdeepin/go-x11-client";
    fetch = {
      type = "git";
      url = "https://github.com/linuxdeepin/go-x11-client";
      rev = "c22b2003577b797880cd2cc6f4df6b16a092cda2";
      sha256 = "1lbgr6iy3hlg9dl6llls88cpy1v75pkkkppsh4mhjgvgly34wcjq";
    };
  }
  {
    goPackagePath = "github.com/msteinert/pam";
    fetch = {
      type = "git";
      url = "https://github.com/msteinert/pam";
      rev = "f4cd9f5e29232537a12db1678f48c702ad6896b7";
      sha256 = "1vjawxswy3f23v4d72kk95y3b557580670ai9ffvrwy6wy85qync";
    };
  }
  {
    goPackagePath = "github.com/nfnt/resize";
    fetch = {
      type = "git";
      url = "https://github.com/nfnt/resize";
      rev = "83c6a9932646f83e3267f353373d47347b6036b2";
      sha256 = "005cpiwq28krbjf0zjwpfh63rp4s4is58700idn24fs3g7wdbwya";
    };
  }
  {
    goPackagePath = "golang.org/x/image";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/image";
      rev = "cd38e8056d9b27bb2f265effa37fb0ea6b8a7f0f";
      sha256 = "0590j5lb5gh57aaj0vbswsq5hcvvrla6nzm3ghls7jh7rxrxjaql";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "891ebc4b82d6e74f468c533b06f983c7be918a96";
      sha256 = "1rgw5gl2lc6bkmsx0fak84s6zdc1bhzfxgqg4mg4yh5hlnhpwrki";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "17bcc049122f272a32787ba38073ee47433023e9";
      sha256 = "0f5kirkbfc1ysvd6ly873vgg7pfigi980235y2d011f4v0mclzpd";
    };
  }
  {
    goPackagePath = "gopkg.in/alecthomas/kingpin.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/alecthomas/kingpin.v2";
      rev = "947dcec5ba9c011838740e680966fd7087a71d0d";
      sha256 = "0mndnv3hdngr3bxp7yxfd47cas4prv98sqw534mx7vp38gd88n5r";
    };
  }
  {
    goPackagePath = "pkg.deepin.io/lib";
    fetch = {
      type = "git";
      url = "https://github.com/linuxdeepin/go-lib.git";
      rev = "4d9427f49e7ce0d4c50beece26f9f86d473401e1";
      sha256 = "0lkyzlbxmq1mw0g3pqr5sasb6zr4rl9vb49907zq61aqhgk5dgb6";
    };
  }
]
